name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            cjke/devops-beginner-challenge-cybershield:latest
            cjke/devops-beginner-challenge-cybershield:${{ github.sha }}

   - name: Deploy to Railway
  if: always()
  env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  run: |
    set -x  # Enable command trace for debugging
    echo "=== Starting Railway Deployment Step ==="
    
    # Install Railway CLI
    npm install -g @railway/cli

    # Log in to Railway using the token
    echo "Logging in to Railway"
    echo $RAILWAY_TOKEN | railway login

    # Link your project
    echo "Linking Railway project with ID: $RAILWAY_PROJECT_ID"
    railway link $RAILWAY_PROJECT_ID

    # Take down any existing deployment (ignore errors if not found)
    echo "Taking down existing Railway deployment (if any)"
    railway down --detach || true

    # Bring up a new deployment forcing a refresh
    echo "Starting new Railway deployment"
    railway up --detach --force

    echo "=== Railway Deployment Step Completed ==="
