name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            cjke/devops-beginner-challenge-cybershield:latest
            cjke/devops-beginner-challenge-cybershield:${{ github.sha }}

   - name: Deploy to Railway
  if: always()
  env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  run: |
    npm install -g @railway/cli
    echo $RAILWAY_TOKEN | railway login
    railway link $RAILWAY_PROJECT_ID
    railway down --detach || true
    railway up --detach --force

  


      - name: Deploy to Local Server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.LOCAL_SERVER_SSH_HOST }}
          username: ${{ secrets.LOCAL_SERVER_SSH_USER }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            docker pull cjke/devops-beginner-challenge-cybershield:${{ github.sha }}
            docker stop devops-beginner-challenge-cybershield || true
            docker rm devops-beginner-challenge-cybershield || true
            docker run -d -p 5000:5000 --name devops-beginner-challenge-cybershield cjke/devops-beginner-challenge-cybershield:${{ github.sha }}
