name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            cjke/devops-beginner-challenge-cybershield:latest
            cjke/devops-beginner-challenge-cybershield:${{ github.sha }}

 - name: Deploy to Railway
  if: always()
  env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  run: |
    set -x
    echo "=== Starting Railway Deployment Step ==="
    npm install -g @railway/cli
    echo "Logging into Railway..."
    printf "%s\n" "$RAILWAY_TOKEN" | railway login
    echo "Linking Railway project with ID: $RAILWAY_PROJECT_ID"
    railway link $RAILWAY_PROJECT_ID
    echo "Taking down any existing deployment..."
    railway down --detach || true
    echo "Starting new deployment with --force and --debug (will timeout in 120 seconds if hanging)..."
    timeout 120 railway up --detach --force --debug || echo "railway up command timed out"
    echo "=== Railway Deployment Step Completed ==="
  